### ISSUE TITLE
[Bug] ID not found

### ISSUE THREAD

**Issue by tmaex** [seandrickson/YOURLS-QRCode-Plugin#12]
The function `sean_toggle_qr(id)` is called twice during creation of shortlinks.
Second time with `id=nourl_found` which breaks the excection as `.attr(href)` can't be called on `undefinded`:
https://github.com/seandrickson/YOURLS-QRCode-Plugin/blob/47d4942d7d8444037824c6596655f38c1c69ef3d/seans-qrcode/plugin.php#L165

This annoyingly leads to the necessity of reloading the page before creating the next shortlink.

**Comment by seandrickson** [comment]
I've taken your fix into the codebase. That should resolve the issue. Thank you!
