### ISSUE TITLE
Outfile

### ISSUE THREAD

**Issue by Hitan22** [seandrickson/YOURLS-QRCode-Plugin#6]
Hi Sean,

Its not so much an issue but i am new to php i need help to configure the outfile. what should i be putting there? I would like to save the qr codes in a directory

**Comment by seandrickson** [comment]
I am using the PHP QRCode Library with the `QRcode::png()` function:
https://github.com/seandrickson/YOURLS-QRCode-Plugin/blob/master/seans-qrcode/plugin.php#L67

Please reference the PHP QRCode Library documentation about how you could leverage their functions to save to a directory on the server (this is the reference to the function used for the plugin):
http://phpqrcode.sourceforge.net/docs/html/class_q_rcode.html#a1b90c0989105afa06b6e1c718a454fb5
